---
title: "Splines"
author: "tommaso tarchi"
date: "2023-01-18"
output: 
  html_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
## importing the dataset and omitting the missing values
datafile <- read.csv("../WiscNursingHome.csv")
datafile <- na.omit(datafile)

## dividing data from different years
data_2000 <- datafile[datafile$CRYEAR == 2000, ]
data_2001 <- datafile[datafile$CRYEAR == 2001, ]

datafile$ORGSTR <- as.factor(datafile$ORGSTR)
datafile$MSA <- as.factor(datafile$MSA)
```

```{r}
library(ggplot2)
library(GGally)
library(splines)
```



```{r}
data_2000$UTILIZATION_RATE <- data_2000$TPY / data_2000$NUMBED
summary(data_2000$UTILIZATION_RATE)

data_trunc <- data_2000[data_2000$UTILIZATION_RATE > 0.89 & data_2000$UTILIZATION_RATE < 0.96, ]
```

```{r}
fit.trunc1 <- lm(log(TPY) ~ log(NUMBED) + log(SQRFOOT), data = data_trunc)
fit.trunc2 <- lm(log(TPY) ~ log(NUMBED) + SQRFOOT, data = data_trunc)
fit.trunc3 <- lm(log(TPY) ~ NUMBED + log(SQRFOOT), data = data_trunc)
fit.trunc4 <- lm(log(TPY) ~ NUMBED + SQRFOOT, data = data_trunc)
summary(fit.trunc1); summary(fit.trunc2); summary(fit.trunc3); summary(fit.trunc4)
```
```{r}
par(mfrow = c(2, 2))
plot(fit.trunc1)
```
```{r}
par(mfrow = c(2, 2))
plot(fit.trunc2)
```
```{r}
par(mfrow = c(2, 2))
plot(fit.trunc3)
```
```{r}
par(mfrow = c(2, 2))
plot(fit.trunc4)
```

